version: '2'

services:
  zookeeper:
    image: bitnami/zookeeper:3
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: bitnami/kafka:2
    ports:
     - 9092:9092
     - 9094:9094  
    volumes:
      - kafka_data:/bitnami
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS= INSIDE://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENERS= INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME= INSIDE
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
